const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate a certificate PDF and return as buffer
 */
async function generateCertificate({ name, eventName, date, templatePath }) {
   return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
         size: 'A4',
         layout: 'landscape',
         margin: 0
      });

      const buffers = [];
      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const pageWidth = doc.page.width;
      const pageHeight = doc.page.height;

      // ─── Background ───
      // Outer gold border
      doc.rect(0, 0, pageWidth, pageHeight).fill('#1a1a2e');

      // Decorative gradient-like border
      const borderColors = ['#e8c56f', '#d4a843'];
      doc.rect(15, 15, pageWidth - 30, pageHeight - 30)
         .strokeColor('#c9a227').lineWidth(3).stroke();
      doc.rect(22, 22, pageWidth - 44, pageHeight - 44)
         .strokeColor('#e8c56f').lineWidth(1).stroke();

      // Inner panel
      doc.rect(40, 40, pageWidth - 80, pageHeight - 80)
         .fill('#16213e');

      // Corner decorations
      const corners = [[50, 50], [pageWidth - 50, 50], [50, pageHeight - 50], [pageWidth - 50, pageHeight - 50]];
      corners.forEach(([x, y]) => {
         doc.circle(x, y, 8).fillColor('#e8c56f').fill();
      });

      // ─── Header ───
      doc.font('Helvetica-Bold')
         .fontSize(11)
         .fillColor('#e8c56f')
         .text('CERTIFICATE OF PARTICIPATION', 0, 65, { align: 'center' });

      // Gold line under header
      doc.moveTo(pageWidth / 2 - 160, 88)
         .lineTo(pageWidth / 2 + 160, 88)
         .strokeColor('#e8c56f').lineWidth(1.5).stroke();

      // Medal icon (unicode star)
      doc.font('Helvetica-Bold')
         .fontSize(36)
         .fillColor('#e8c56f')
         .text('★', 0, 100, { align: 'center' });

      // ─── This is to certify ───
      doc.font('Helvetica')
         .fontSize(13)
         .fillColor('#ccc')
         .text('This is to certify that', 0, 155, { align: 'center' });

      // ─── Recipient Name ───
      doc.font('Helvetica-Bold')
         .fontSize(36)
         .fillColor('#ffffff')
         .text(name, 0, 178, { align: 'center' });

      // Underline for name
      const nameWidth = doc.widthOfString(name, { fontSize: 36 });
      const nameX = (pageWidth - Math.min(nameWidth, 400)) / 2;
      doc.moveTo(nameX, 222)
         .lineTo(pageWidth - nameX, 222)
         .strokeColor('#e8c56f').lineWidth(1).stroke();

      // ─── Participation Text ───
      doc.font('Helvetica')
         .fontSize(13)
         .fillColor('#ccc')
         .text('has successfully participated in', 0, 232, { align: 'center' });

      // ─── Event Name ───
      doc.font('Helvetica-Bold')
         .fontSize(22)
         .fillColor('#e8c56f')
         .text(eventName, 0, 254, { align: 'center' });

      // ─── Date ───
      doc.font('Helvetica')
         .fontSize(12)
         .fillColor('#aaa')
         .text(`Held on ${date}`, 0, 288, { align: 'center' });

      // ─── Footer line ───
      doc.moveTo(pageWidth / 2 - 180, 335)
         .lineTo(pageWidth / 2 + 180, 335)
         .strokeColor('#555').lineWidth(1).stroke();

      // ─── Signature placeholders ───
      doc.font('Helvetica')
         .fontSize(10)
         .fillColor('#aaa')
         .text('_________________________', 100, 345)
         .text('Organizer Signature', 100, 362)
         .text('_________________________', pageWidth - 280, 345)
         .text('Event Coordinator', pageWidth - 280, 362);

      // ─── Watermark / ID ───
      doc.font('Helvetica')
         .fontSize(8)
         .fillColor('#444')
         .text(`Generated by Event Management System | ${new Date().toISOString()}`, 0, pageHeight - 52, { align: 'center' });

      doc.end();
   });
}

module.exports = { generateCertificate };
