const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const nodemailer = require('nodemailer');
const { EmailLog } = require('./models');
const { Settings } = require('./models');

module.exports = {};

// --- certificateService.js ---
/**
 * Generate a certificate PDF and return as buffer
 */
async function generateCertificate({ name, eventName, date, templatePath }) {
   return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
         size: 'A4',
         layout: 'landscape',
         margin: 0
      });

      const buffers = [];
      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const pageWidth = doc.page.width;
      const pageHeight = doc.page.height;

      // ─── Background ───
      // Outer gold border
      doc.rect(0, 0, pageWidth, pageHeight).fill('#1a1a2e');

      // Decorative gradient-like border
      const borderColors = ['#e8c56f', '#d4a843'];
      doc.rect(15, 15, pageWidth - 30, pageHeight - 30)
         .strokeColor('#c9a227').lineWidth(3).stroke();
      doc.rect(22, 22, pageWidth - 44, pageHeight - 44)
         .strokeColor('#e8c56f').lineWidth(1).stroke();

      // Inner panel
      doc.rect(40, 40, pageWidth - 80, pageHeight - 80)
         .fill('#16213e');

      // Corner decorations
      const corners = [[50, 50], [pageWidth - 50, 50], [50, pageHeight - 50], [pageWidth - 50, pageHeight - 50]];
      corners.forEach(([x, y]) => {
         doc.circle(x, y, 8).fillColor('#e8c56f').fill();
      });

      // ─── Header ───
      doc.font('Helvetica-Bold')
         .fontSize(11)
         .fillColor('#e8c56f')
         .text('CERTIFICATE OF PARTICIPATION', 0, 65, { align: 'center' });

      // Gold line under header
      doc.moveTo(pageWidth / 2 - 160, 88)
         .lineTo(pageWidth / 2 + 160, 88)
         .strokeColor('#e8c56f').lineWidth(1.5).stroke();

      // Medal icon (unicode star)
      doc.font('Helvetica-Bold')
         .fontSize(36)
         .fillColor('#e8c56f')
         .text('★', 0, 100, { align: 'center' });

      // ─── This is to certify ───
      doc.font('Helvetica')
         .fontSize(13)
         .fillColor('#ccc')
         .text('This is to certify that', 0, 155, { align: 'center' });

      // ─── Recipient Name ───
      doc.font('Helvetica-Bold')
         .fontSize(36)
         .fillColor('#ffffff')
         .text(name, 0, 178, { align: 'center' });

      // Underline for name
      const nameWidth = doc.widthOfString(name, { fontSize: 36 });
      const nameX = (pageWidth - Math.min(nameWidth, 400)) / 2;
      doc.moveTo(nameX, 222)
         .lineTo(pageWidth - nameX, 222)
         .strokeColor('#e8c56f').lineWidth(1).stroke();

      // ─── Participation Text ───
      doc.font('Helvetica')
         .fontSize(13)
         .fillColor('#ccc')
         .text('has successfully participated in', 0, 232, { align: 'center' });

      // ─── Event Name ───
      doc.font('Helvetica-Bold')
         .fontSize(22)
         .fillColor('#e8c56f')
         .text(eventName, 0, 254, { align: 'center' });

      // ─── Date ───
      doc.font('Helvetica')
         .fontSize(12)
         .fillColor('#aaa')
         .text(`Held on ${date}`, 0, 288, { align: 'center' });

      // ─── Footer line ───
      doc.moveTo(pageWidth / 2 - 180, 335)
         .lineTo(pageWidth / 2 + 180, 335)
         .strokeColor('#555').lineWidth(1).stroke();

      // ─── Signature placeholders ───
      doc.font('Helvetica')
         .fontSize(10)
         .fillColor('#aaa')
         .text('_________________________', 100, 345)
         .text('Organizer Signature', 100, 362)
         .text('_________________________', pageWidth - 280, 345)
         .text('Event Coordinator', pageWidth - 280, 362);

      // ─── Watermark / ID ───
      doc.font('Helvetica')
         .fontSize(8)
         .fillColor('#444')
         .text(`Generated by Event Management System | ${new Date().toISOString()}`, 0, pageHeight - 52, { align: 'center' });

      doc.end();
   });
}


// Exported from certificateService.js
Object.assign(module.exports, { generateCertificate });

// --- emailService.js ---
require('dotenv').config();




const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT) || 587,
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS
  }
});

/**
 * Send a single email and log it.
 * fromName/fromEmail are loaded from DB Settings (admin-configured).
 */
async function sendEmail({ to, toName, subject, html, type, eventId, attachments = [] }) {
  // Load admin-configured sender details from DB, fallback to .env
  const settings = await Settings.getSettings();
  const fromName  = settings.fromName  || process.env.FROM_NAME  || 'Event Team';
  const fromEmail = settings.fromEmail || process.env.FROM_EMAIL || process.env.SMTP_USER;

  const mailOptions = {
    from: `"${fromName}" <${fromEmail}>`,
    to,
    subject,
    html,
    attachments,
    ...(settings.replyTo ? { replyTo: settings.replyTo } : {})
  };

  try {
    await transporter.sendMail(mailOptions);

    await EmailLog.create({
      eventId,
      recipientEmail: to,
      recipientName: toName,
      type,
      subject,
      status: 'sent'
    });

    return { success: true };
  } catch (err) {
    await EmailLog.create({
      eventId,
      recipientEmail: to,
      recipientName: toName,
      type,
      subject,
      status: 'failed',
      errorMessage: err.message
    });

    return { success: false, error: err.message };
  }
}


/**
 * Send bulk emails with duplicate/failure handling
 */
async function sendBulkEmails(emailList) {
  const results = { sent: 0, failed: 0, errors: [] };

  for (const emailData of emailList) {
    const result = await sendEmail(emailData);
    if (result.success) {
      results.sent++;
    } else {
      results.failed++;
      results.errors.push({ email: emailData.to, error: result.error });
    }
    // Small delay to avoid rate limiting
    await new Promise(res => setTimeout(res, 150));
  }

  return results;
}


// Exported from emailService.js
Object.assign(module.exports, { sendEmail, sendBulkEmails, transporter });

// --- emailTemplates.js ---
/**
 * Email Templates
 */

function promotionTemplate({ eventName, eventDate, eventVenue, eventDescription, collegeNam, customMessage }) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 30px auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 30px; text-align: center; }
    .header h1 { color: #fff; margin: 0; font-size: 28px; letter-spacing: 1px; }
    .header p { color: rgba(255,255,255,0.85); margin: 8px 0 0; font-size: 14px; }
    .body { padding: 35px 30px; }
    .event-card { background: #f8f9ff; border-left: 4px solid #667eea; border-radius: 8px; padding: 20px; margin: 20px 0; }
    .event-card h2 { color: #333; margin: 0 0 10px; font-size: 20px; }
    .detail { display: flex; align-items: center; margin: 8px 0; color: #555; font-size: 14px; }
    .detail span { font-weight: bold; min-width: 80px; color: #444; }
    .cta-btn { display: block; width: fit-content; margin: 25px auto; padding: 14px 35px; background: linear-gradient(135deg, #667eea, #764ba2); color: #fff; text-decoration: none; border-radius: 30px; font-size: 15px; font-weight: bold; text-align: center; }
    .footer { background: #f4f6f9; padding: 20px 30px; text-align: center; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🎉 You're Invited!</h1>
      <p>An exciting event awaits your college</p>
    </div>
    <div class="body">
      <p>Dear <strong>${collegeNam || 'Team'}</strong>,</p>
      <p>We are thrilled to invite your college to participate in our upcoming event!</p>
      
      <div class="event-card">
        <h2>📅 ${eventName}</h2>
        <div class="detail"><span>Date:</span> ${eventDate}</div>
        <div class="detail"><span>Venue:</span> ${eventVenue || 'To be announced'}</div>
        ${eventDescription ? `<p style="color:#555;margin-top:10px;">${eventDescription}</p>` : ''}
      </div>

      ${customMessage ? `<p style="color:#444;line-height:1.7;">${customMessage}</p>` : ''}
      
      <p>We look forward to your enthusiastic participation!</p>
    </div>
    <div class="footer">
      <p>This is a promotional email. If you have questions, please reply to this email.</p>
    </div>
  </div>
</body>
</html>`;
}

function confirmationTemplate({ name, eventName, eventDate, eventVenue }) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 30px auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #11998e, #38ef7d); padding: 40px 30px; text-align: center; }
    .header h1 { color: #fff; margin: 0; font-size: 26px; }
    .body { padding: 35px 30px; color: #444; line-height: 1.7; }
    .badge { background: #e8fff2; border: 2px solid #38ef7d; border-radius: 50px; padding: 10px 25px; display: inline-block; margin: 15px 0; color: #11998e; font-weight: bold; font-size: 15px; }
    .info-box { background: #f0f9ff; border-radius: 8px; padding: 20px; margin: 20px 0; }
    .footer { background: #f4f6f9; padding: 20px; text-align: center; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>✅ Registration Confirmed!</h1>
    </div>
    <div class="body">
      <p>Dear <strong>${name}</strong>,</p>
      <div class="badge">🎊 You're Registered!</div>
      <p>Your registration for <strong>${eventName}</strong> has been successfully received.</p>
      <div class="info-box">
        <p><strong>📅 Event Date:</strong> ${eventDate}</p>
        <p><strong>📍 Venue:</strong> ${eventVenue || 'To be announced'}</p>
      </div>
      <p><strong>⏳ Next Steps:</strong> Our team will review registrations and notify you about your shortlisting status shortly. Please wait for further communication.</p>
      <p>Thank you for registering! We'll keep you updated.</p>
    </div>
    <div class="footer"><p>Sent by Event Management System</p></div>
  </div>
</body>
</html>`;
}

function shortlistedTemplate({ name, eventName, eventDate, eventVenue, instructions }) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 30px auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #f7971e, #ffd200); padding: 40px 30px; text-align: center; }
    .header h1 { color: #333; margin: 0; font-size: 26px; }
    .body { padding: 35px 30px; color: #444; line-height: 1.7; }
    .star-badge { font-size: 50px; text-align: center; margin: 10px 0; }
    .info-box { background: #fffbe6; border-left: 4px solid #ffd200; border-radius: 8px; padding: 20px; margin: 20px 0; }
    .footer { background: #f4f6f9; padding: 20px; text-align: center; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🌟 Congratulations! You're Shortlisted!</h1>
    </div>
    <div class="body">
      <p>Dear <strong>${name}</strong>,</p>
      <div class="star-badge">🏆</div>
      <p>We are delighted to inform you that you have been <strong>shortlisted</strong> to participate in <strong>${eventName}</strong>!</p>
      <div class="info-box">
        <p><strong>📅 Event Date:</strong> ${eventDate}</p>
        <p><strong>📍 Venue:</strong> ${eventVenue || 'To be announced'}</p>
      </div>
      ${instructions ? `<p><strong>📌 Instructions:</strong><br>${instructions}</p>` : ''}
      <p>Please be prepared and on time. A reminder email will be sent before the event.</p>
      <p>All the best! 💪</p>
    </div>
    <div class="footer"><p>Sent by Event Management System</p></div>
  </div>
</body>
</html>`;
}

function rejectedTemplate({ name, eventName }) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 30px auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #636363, #a2a2a2); padding: 40px 30px; text-align: center; }
    .header h1 { color: #fff; margin: 0; font-size: 24px; }
    .body { padding: 35px 30px; color: #444; line-height: 1.7; }
    .footer { background: #f4f6f9; padding: 20px; text-align: center; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Thank You for Participating</h1>
    </div>
    <div class="body">
      <p>Dear <strong>${name}</strong>,</p>
      <p>Thank you for registering for <strong>${eventName}</strong>.</p>
      <p>We regret to inform you that you have not been shortlisted for this event. We had many talented participants and the selection was very competitive.</p>
      <p>Please don't be disheartened. We encourage you to participate in our future events. Your enthusiasm means a lot to us!</p>
      <p>Thank you for your interest. Keep going! 💙</p>
    </div>
    <div class="footer"><p>Sent by Event Management System</p></div>
  </div>
</body>
</html>`;
}

function reminderTemplate({ name, eventName, eventDate, eventVenue }) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 30px auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #fc466b, #3f5efb); padding: 40px 30px; text-align: center; }
    .header h1 { color: #fff; margin: 0; font-size: 26px; }
    .body { padding: 35px 30px; color: #444; line-height: 1.7; }
    .countdown { background: linear-gradient(135deg, #fc466b, #3f5efb); color: #fff; border-radius: 10px; padding: 20px; text-align: center; margin: 20px 0; font-size: 22px; font-weight: bold; }
    .checklist { background: #f8f9ff; border-radius: 8px; padding: 20px; margin: 20px 0; }
    .checklist li { margin: 8px 0; color: #555; }
    .footer { background: #f4f6f9; padding: 20px; text-align: center; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>⏰ Event Tomorrow — Don't Miss It!</h1>
    </div>
    <div class="body">
      <p>Dear <strong>${name}</strong>,</p>
      <div class="countdown">🚀 ${eventName} is TOMORROW!</div>
      <p><strong>📅 Date:</strong> ${eventDate}<br><strong>📍 Venue:</strong> ${eventVenue || 'To be announced'}</p>
      <div class="checklist">
        <p><strong>✅ Pre-Event Checklist:</strong></p>
        <ul>
          <li>Confirm your attendance and team members</li>
          <li>Carry your ID card and registration confirmation</li>
          <li>Reach the venue 15 minutes early</li>
          <li>Bring any required materials</li>
        </ul>
      </div>
      <p>We are excited to see you tomorrow! Good luck! 🎉</p>
    </div>
    <div class="footer"><p>Sent by Event Management System</p></div>
  </div>
</body>
</html>`;
}

function certificateEmailTemplate({ name, eventName }) {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 30px auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #f093fb, #f5576c); padding: 40px 30px; text-align: center; }
    .header h1 { color: #fff; margin: 0; font-size: 26px; }
    .body { padding: 35px 30px; color: #444; line-height: 1.7; }
    .cert-badge { background: linear-gradient(135deg, #f093fb20, #f5576c20); border: 2px solid #f5576c; border-radius: 10px; padding: 20px; text-align: center; margin: 20px 0; }
    .footer { background: #f4f6f9; padding: 20px; text-align: center; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🏅 Your Certificate of Participation</h1>
    </div>
    <div class="body">
      <p>Dear <strong>${name}</strong>,</p>
      <div class="cert-badge">
        <p style="font-size:40px;margin:0">🎓</p>
        <p style="font-weight:bold;color:#f5576c;margin:5px 0">Certificate Attached!</p>
      </div>
      <p>Congratulations on successfully participating in <strong>${eventName}</strong>!</p>
      <p>Please find your <strong>Certificate of Participation</strong> attached to this email. This certificate recognizes your dedication and contribution to the event.</p>
      <p>We hope to see you at more of our events in the future. Keep up the great work!</p>
      <p>Best regards,<br><strong>Event Management Team</strong></p>
    </div>
    <div class="footer"><p>Sent by Event Management System | Certificate attached as PDF</p></div>
  </div>
</body>
</html>`;
}


// Exported from emailTemplates.js
Object.assign(module.exports, {
  promotionTemplate,
  confirmationTemplate,
  shortlistedTemplate,
  rejectedTemplate,
  reminderTemplate,
  certificateEmailTemplate
});
