import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import api from './api';

const EMAIL_TYPES = [
  { value: 'confirmation', label: '✅ Confirmation',  desc: 'Registration successful email',        group: 'registered' },
  { value: 'shortlisted',  label: '🌟 Shortlisted',   desc: 'Shortlist announcement email',         group: 'shortlisted' },
  { value: 'reminder',     label: '⏰ Reminder',       desc: 'Event reminder for shortlisted',       group: 'shortlisted' },
  { value: 'rejection',    label: '❌ Rejection',      desc: 'Polite rejection for non-shortlisted', group: 'rejected' },
  { value: 'promotion',    label: '📣 Promotion',      desc: 'Promotional email to colleges',        group: 'colleges' },
  { value: 'custom',       label: '✉️ Custom',         desc: 'Any custom message',                   group: 'all_registrations' },
];

const TONES = [
  { value: 'professional', label: '💼 Professional' },
  { value: 'friendly',     label: '😊 Friendly' },
  { value: 'exciting',     label: '🚀 Exciting' },
  { value: 'formal',       label: '🎩 Formal' },
];

const TARGET_GROUPS = [
  { value: 'registered',        label: '📋 All Registered Students' },
  { value: 'shortlisted',       label: '⭐ Shortlisted Students' },
  { value: 'rejected',          label: '❌ Rejected Students' },
  { value: 'all_registrations', label: '👥 All Students (Registered + Shortlisted)' },
  { value: 'colleges',          label: '🏫 All Colleges' },
];

export default function Compose() {
  const [mode, setMode] = useState('ai'); // 'ai' | 'manual'
  const [events, setEvents] = useState([]);
  const [selectedEvent, setSelectedEvent] = useState('');
  const [emailType, setEmailType] = useState('confirmation');
  const [tone, setTone] = useState('professional');
  const [customNote, setCustomNote] = useState('');
  const [targetGroup, setTargetGroup] = useState('registered');
  const [subject, setSubject] = useState('');
  const [htmlBody, setHtmlBody] = useState('');
  const [generating, setGenerating] = useState(false);
  const [sending, setSending] = useState(false);
  const [recipientCount, setRecipientCount] = useState(null);
  const [previewMode, setPreviewMode] = useState('html'); // 'html' | 'code'
  const [sendResult, setSendResult] = useState(null);

  useEffect(() => {
    api.get('/events').then(({ data }) => setEvents(data)).catch(() => {});
  }, []);

  // Auto-set target group when email type changes
  useEffect(() => {
    const t = EMAIL_TYPES.find(e => e.value === emailType);
    if (t) setTargetGroup(t.group);
  }, [emailType]);

  // Fetch recipient count when group or event changes
  useEffect(() => {
    if (!targetGroup) return;
    const params = new URLSearchParams({ targetGroup });
    if (selectedEvent) params.append('eventId', selectedEvent);
    api.get(`/compose/recipients-count?${params}`)
      .then(({ data }) => setRecipientCount(data.count))
      .catch(() => setRecipientCount(null));
  }, [targetGroup, selectedEvent]);

  const selectedEventObj = events.find(e => e._id === selectedEvent);

  const handleGenerate = async () => {
    if (!selectedEventObj && emailType !== 'promotion') {
      return toast.error('Select an event first');
    }
    setGenerating(true); setSendResult(null);
    try {
      const { data } = await api.post('/compose/generate', {
        emailType,
        eventName:        selectedEventObj?.name        || 'Your Event',
        eventDate:        selectedEventObj?.date        ? new Date(selectedEventObj.date).toLocaleDateString('en-IN', { dateStyle: 'long' }) : '',
        eventVenue:       selectedEventObj?.venue       || '',
        eventDescription: selectedEventObj?.description || '',
        customNote,
        tone
      });
      setSubject(data.subject);
      setHtmlBody(data.html);
      toast.success('✨ Email generated by AI!');
    } catch (err) {
      toast.error(err.response?.data?.error || 'AI generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const handleSend = async () => {
    if (!subject.trim()) return toast.error('Subject is required');
    if (!htmlBody.trim()) return toast.error('Email body is required');
    if (!targetGroup) return toast.error('Select a target group');
    if (targetGroup !== 'colleges' && !selectedEvent) return toast.error('Select an event');

    const confirmed = window.confirm(
      `Send this email to ${recipientCount ?? '?'} ${targetGroup === 'colleges' ? 'colleges' : 'students'}?\n\nSubject: ${subject}`
    );
    if (!confirmed) return;

    setSending(true); setSendResult(null);
    try {
      const { data } = await api.post('/compose/send', {
        eventId: selectedEvent || null,
        subject,
        html: htmlBody,
        targetGroup,
        emailType
      });
      setSendResult(data);
      toast.success(`✅ Sent ${data.sent} emails!`);
    } catch (err) {
      toast.error(err.response?.data?.error || 'Failed to send emails');
    } finally {
      setSending(false);
    }
  };

  return (
    <div>
      <div className="page-header">
        <h1>✍️ Email Composer</h1>
        <p>Compose and send custom or AI-generated emails to students and colleges</p>
      </div>

      <div style={{ display: 'flex', gap: 24, flexWrap: 'wrap', alignItems: 'flex-start' }}>

        {/* ── Left Panel: Controls ── */}
        <div style={{ flex: '0 0 380px', minWidth: 320, display: 'flex', flexDirection: 'column', gap: 16 }}>

          {/* Mode Toggle */}
          <div className="card" style={{ padding: '12px 16px' }}>
            <div style={{ display: 'flex', gap: 0, background: 'var(--bg-card2)', borderRadius: 8, padding: 4 }}>
              {[['ai', '✨ AI Generated'], ['manual', '✏️ Write Manually']].map(([v, l]) => (
                <button key={v} onClick={() => setMode(v)} style={{
                  flex: 1, padding: '8px 12px', border: 'none', borderRadius: 6, cursor: 'pointer', fontSize: 13, fontWeight: 600,
                  background: mode === v ? 'var(--primary)' : 'transparent',
                  color: mode === v ? '#fff' : 'var(--text-secondary)',
                  transition: 'all 0.2s'
                }}>{l}</button>
              ))}
            </div>
          </div>

          {/* Email Type */}
          <div className="card">
            <div className="section-title" style={{ marginBottom: 10 }}>📧 Email Type</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {EMAIL_TYPES.map(t => (
                <label key={t.value} style={{
                  display: 'flex', alignItems: 'center', gap: 10, padding: '10px 12px',
                  background: emailType === t.value ? 'rgba(124,58,237,0.15)' : 'var(--bg-card2)',
                  border: `1px solid ${emailType === t.value ? 'var(--primary)' : 'var(--border)'}`,
                  borderRadius: 8, cursor: 'pointer', transition: 'all 0.2s'
                }}>
                  <input type="radio" name="emailType" value={t.value}
                    checked={emailType === t.value} onChange={() => setEmailType(t.value)}
                    style={{ accentColor: 'var(--primary)' }} />
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 600 }}>{t.label}</div>
                    <div style={{ fontSize: 11, color: 'var(--text-secondary)' }}>{t.desc}</div>
                  </div>
                </label>
              ))}
            </div>
          </div>

          {/* Event Selector */}
          <div className="card">
            <div className="section-title" style={{ marginBottom: 10 }}>🎯 Select Event</div>
            <select className="form-control" value={selectedEvent} onChange={e => setSelectedEvent(e.target.value)}>
              <option value="">— {emailType === 'promotion' ? 'Optional for promotion' : 'Select event'} —</option>
              {events.map(e => (
                <option key={e._id} value={e._id}>{e.name} ({new Date(e.date).toLocaleDateString('en-IN')})</option>
              ))}
            </select>
          </div>

          {/* Target Group */}
          <div className="card">
            <div className="section-title" style={{ marginBottom: 10 }}>👥 Send To</div>
            <select className="form-control" value={targetGroup} onChange={e => setTargetGroup(e.target.value)}>
              {TARGET_GROUPS.map(g => (
                <option key={g.value} value={g.value}>{g.label}</option>
              ))}
            </select>
            {recipientCount !== null && (
              <div style={{
                marginTop: 10, padding: '8px 12px', background: 'rgba(124,58,237,0.1)',
                border: '1px solid rgba(124,58,237,0.3)', borderRadius: 8,
                fontSize: 13, color: 'var(--primary)', fontWeight: 600
              }}>
                📬 {recipientCount} recipient{recipientCount !== 1 ? 's' : ''} will receive this email
              </div>
            )}
          </div>

          {/* AI Options */}
          {mode === 'ai' && (
            <div className="card">
              <div className="section-title" style={{ marginBottom: 10 }}>🤖 AI Options</div>
              <div className="form-group">
                <label className="form-label">Tone</label>
                <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                  {TONES.map(t => (
                    <button key={t.value} onClick={() => setTone(t.value)} style={{
                      padding: '6px 12px', borderRadius: 20, border: `1px solid ${tone === t.value ? 'var(--primary)' : 'var(--border)'}`,
                      background: tone === t.value ? 'rgba(124,58,237,0.15)' : 'transparent',
                      color: tone === t.value ? 'var(--primary)' : 'var(--text-secondary)',
                      cursor: 'pointer', fontSize: 12, fontWeight: 500
                    }}>{t.label}</button>
                  ))}
                </div>
              </div>
              <div className="form-group">
                <label className="form-label">Additional Instructions (Optional)</label>
                <textarea className="form-control" value={customNote} rows={3}
                  onChange={e => setCustomNote(e.target.value)}
                  placeholder="e.g. Mention that participants must bring their ID card, mention prize pool of ₹50,000..." />
              </div>
              <button className="btn btn-primary" style={{ width: '100%' }}
                onClick={handleGenerate} disabled={generating}>
                {generating
                  ? <><span className="spinner" />Generating with AI...</>
                  : '✨ Generate Email with AI'}
              </button>
            </div>
          )}
        </div>

        {/* ── Right Panel: Editor + Preview ── */}
        <div style={{ flex: 1, minWidth: 340, display: 'flex', flexDirection: 'column', gap: 16 }}>

          {/* Subject */}
          <div className="card">
            <label className="form-label" style={{ marginBottom: 6 }}>📌 Subject Line</label>
            <input className="form-control" placeholder="e.g. 🌟 You're Shortlisted for CodeFest 2025!"
              value={subject} onChange={e => setSubject(e.target.value)} style={{ fontSize: 14 }} />
            <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginTop: 6 }}>
              Use <code style={{ background: 'var(--bg-card2)', padding: '1px 5px', borderRadius: 4 }}>{'{{name}}'}</code> and <code style={{ background: 'var(--bg-card2)', padding: '1px 5px', borderRadius: 4 }}>{'{{eventName}}'}</code> as placeholders
            </div>
          </div>

          {/* Body Editor + Preview tabs */}
          <div className="card" style={{ flex: 1 }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
              <div className="section-title" style={{ margin: 0 }}>📝 Email Body</div>
              <div style={{ display: 'flex', gap: 0, background: 'var(--bg-card2)', borderRadius: 6, padding: 3 }}>
                {[['html', '👁️ Preview'], ['code', '💻 HTML Code']].map(([v, l]) => (
                  <button key={v} onClick={() => setPreviewMode(v)} style={{
                    padding: '5px 12px', border: 'none', borderRadius: 5, cursor: 'pointer', fontSize: 12,
                    background: previewMode === v ? 'var(--primary)' : 'transparent',
                    color: previewMode === v ? '#fff' : 'var(--text-secondary)'
                  }}>{l}</button>
                ))}
              </div>
            </div>

            {previewMode === 'code' ? (
              <textarea className="form-control" rows={18} value={htmlBody}
                onChange={e => setHtmlBody(e.target.value)}
                placeholder={mode === 'ai'
                  ? 'Click "Generate Email with AI" to create content, or paste HTML here...'
                  : 'Write your HTML email body here...\n\nUse {{name}}, {{eventName}}, {{eventDate}}, {{eventVenue}} as placeholders.\n\nYou can also paste plain text — it will be sent as-is.'}
                style={{ fontFamily: 'monospace', fontSize: 12, lineHeight: 1.6, minHeight: 400, resize: 'vertical' }}
              />
            ) : (
              <div style={{
                border: '1px solid var(--border)', borderRadius: 8, overflow: 'hidden',
                background: '#fff', minHeight: 400
              }}>
                {htmlBody ? (
                  <iframe
                    srcDoc={htmlBody}
                    style={{ width: '100%', height: 450, border: 'none' }}
                    title="Email Preview"
                    sandbox="allow-same-origin"
                  />
                ) : (
                  <div style={{ padding: 40, textAlign: 'center', color: '#999' }}>
                    <div style={{ fontSize: 40, marginBottom: 12 }}>📧</div>
                    <div>{mode === 'ai' ? 'Generate an email with AI to see the preview' : 'Write your email HTML to see the preview'}</div>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Placeholder helper */}
          <div className="card" style={{ padding: '12px 16px' }}>
            <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 8 }}>
              <strong>Available placeholders</strong> (auto-replaced on send):
            </div>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {['{{name}}', '{{eventName}}', '{{eventDate}}', '{{eventVenue}}', '{{orgName}}'].map(p => (
                <code key={p} style={{
                  background: 'rgba(124,58,237,0.1)', color: 'var(--primary)',
                  padding: '3px 8px', borderRadius: 4, fontSize: 11, cursor: 'pointer'
                }} onClick={() => {
                  navigator.clipboard.writeText(p);
                  toast.success(`${p} copied!`);
                }}>{p}</code>
              ))}
            </div>
          </div>

          {/* Send Button */}
          <button className="btn btn-primary" style={{ width: '100%', padding: '14px 0', fontSize: 15, fontWeight: 700 }}
            onClick={handleSend} disabled={sending || !subject || !htmlBody}>
            {sending
              ? <><span className="spinner" />Sending to {recipientCount ?? '...'} recipients...</>
              : `📤 Send to ${recipientCount ?? '...'} ${targetGroup === 'colleges' ? 'Colleges' : 'Students'}`}
          </button>

          {/* Result */}
          {sendResult && (
            <div style={{ display: 'flex', gap: 12 }}>
              <div className="alert alert-success" style={{ flex: 1 }}>✅ Sent: <strong>{sendResult.sent}</strong></div>
              {sendResult.failed > 0 && (
                <div className="alert alert-error" style={{ flex: 1 }}>❌ Failed: <strong>{sendResult.failed}</strong></div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
